# My Python journey

## The plan

In a little more than two years from now, I'd like to be graduating the Applied Data Science master at University Utrecht. This minor is a great prerequisite, as it focuses on R and statistics. 
Besides that, however, the master also requires basic knowledge of data-analysis and statistics in Python. While the data-analysis and statistics knowledge overall will be the same, I'll need to know how to do these things using Python.

Therefore, I will spend this course's free time studying Python, with a focus on data-analysis and statistics.
I will start by doing some tutorials on the [BeginnersGuide](https://wiki.python.org/moin/BeginnersGuide/Programmers).
Then, I will do at least [this tutorial](https://towardsdatascience.com/a-beginners-guide-to-data-analysis-in-python-188706df5447) on data-analysis using Python. Maybe more, depending on the time it takes.
After that, I will walk through [this tutorial](https://realpython.com/python-statistics/) to get some insight in how to use statistics in Python. This tutorial also incorporates some data wrangling, so it will be a nice addition.

While I realize that this obviously isn't enough to learn Python, I think it'll make for a great start.

***

## The result

My Python journey ended up being a rough ride. I went to work with Python3 (version 3.8.5) and my first hurdle actually ended up being finding a program to work with. At first, I thought it would be easiest to do it in Rstudio, since I already know how that works. I was wrong. Even just using the help() function kept resulting in a massive error that shut Rstudio down. I went on to try a variety of programs such as Pycharm, .., .. and .., but ended up working with an Ubuntu terminal.
I was very happy to find [this tutorial](https://python.land/python-tutorial), as it really provides a clear explanation, not only on Python itself, but also on how to work with it in other programs. The tutorial also incorporated some info on how to work with Visual Studio code. At first I was rather excited about this, because when I first started doing some programming in C# (about seven years ago) I was also working in Visual Studio. Unfortunately, the tutorial doesn't actually provide any practical tutorials on working with Python in the IDE and I wasn't able to get it to work myself.
I realise this tutorial is very basic, but when looking at a little more advanced stuff I quickly realized I knew absolutely nothing about Python. So, the basics is was. It ended up being a very clear tutorial that really helped me understanding the syntax of the language, as it's rather different from R.
I tried to walk through the second tutorial noted above, but when error after error occurred and I eventually stopped finding answers online, I decided it would be better to use my time otherwise. It did teach me something about working with libraries, loading data into Python and some basic visualisation and data wrangling though, so maybe it wasn't all lost time and energy. I just would've liked to be able to actually try out and play around with some of the examples and the example data. To try and achieve this I decided to give Rstudio antoher shot, but for some reason my terminal and console ended up working wth different versions of Python, so that was probably why I couldn't get it to work. Unfortunately I couldn't fix this in the time I had.
Finally, I tried the final tutorial I listed above. While being a nice refresher on the basics of statistics, it ended up very basic in the actual programming. Because I was only able to work in an Ubuntu terminal, I also couldn't really work with the visualisations, which I thought was a shame.
